// generated by @ldesign/vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LButton: typeof import('@ldesign/desktop-next')['Button']
    LDrawer: typeof import('@ldesign/desktop-next')['Drawer']
    LDropdown: typeof import('@ldesign/desktop-next')['Dropdown']
    LIcon: typeof import('@ldesign/desktop-next')['Icon']
    LRadioButton: typeof import('@ldesign/desktop-next')['RadioButton']
    LRadioGroup: typeof import('@ldesign/desktop-next')['RadioGroup']
    LSpace: typeof import('@ldesign/desktop-next')['Space']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
